#  SPDX-License-Identifier: Apache-2.0
update_last_called:
  # Description of the service
  description: Forces update of last_called echo device for each Alexa account.
  # Different fields that your service accepts
  fields:
    # Key of the field
    email:
      # Description of the field
      description: List of Alexa accounts to update. If empty, will update all known accounts
      # Example value that can be passed for this field
      example: 'my_email@alexa.com'
get_guard_state:
  # Description of the service
  description: Get state of Alexa guard for the Alexa account.
  # Different fields that your service accepts
  fields:
    # Key of the field
    entity:
      # Description of the field
      description: ApplianceId of Alexa Guard device (https://alexa.amazon.com/api/phoenix?includeRelationships=true)
      # Example value that can be passed for this field
      example: 'AAA_OnGuardSmartHomeBridgeService_XXXXX'
    email:
      # Description of the field
      description: List of Alexa accounts to check. If empty, will update all known accounts
      # Example value that can be passed for this field
      example: 'my_email@alexa.com'
set_guard_state:
  # Description of the service
  description: Set state of Alexa guard for the Alexa account.
  # Different fields that your service accepts
  fields:
    # Key of the field
    entity:
      # Description of the field
      description: entityId of Alexa Guard device (https://alexa.amazon.com/api/phoenix?includeRelationships=true)
      # Example value that can be passed for this field
      example: 'UNKNOWN at this time'
    email:
      # Description of the field
      description: List of Alexa accounts to set. If empty, will set all known accounts
      # Example value that can be passed for this field
      example: 'my_email@alexa.com'
    state:
      # Description of the field
      description: The state to set. Allows ARMED_AWAY and ARMED_STAY
      # Example value that can be passed for this field
      example: 'ARMED_AWAY'
